version: '3.7'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://172.21.160.1:5432/sonarqube
      - SONAR_JDBC_USERNAME=root1
      - SONAR_JDBC_PASSWORD=root123
    ports:
      - "9000:9000"
    volumes:
      - ./conf/sonar.properties:/opt/sonarqube/conf/sonar.properties
      - ./extensions/jdbc-driver/postgresql:/opt/sonarqube/extensions/jdbc-driver/postgresql
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge
