title: "Tech Skills Blog"
description: "My journey through AWS, Java, Databases, System Design, and more"
author: "GGurkhude"
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ganeshydv.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "GGurkhude"

# Navigation
header_pages:
  - about.md
  - categories.md

# Social links
github_username: your-username
linkedin_username: your-linkedin

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Exclude files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - generateIndexInMd.js
  - package.json
  - tsconfig.json
