# Simple workflow for deploying static content to GitHub Pages
name: Deploy Jekyll with custom scripts

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}
      
      - name: Setup Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
      
      - name: Setup Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          echo 'export PATH="$HOME/.gem/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          gem install jekyll bundler
      
      - name: Install dependencies
        run: |
          bundle install
      
      - name: Run conversion script
        run: |
          echo "Converting markdown files to Jekyll posts..."
          node convert-to-jekyll.js
      
      - name: Build with Jekyll
        run: |
          bundle exec jekyll build
      
      - name: Setup Pages
        run: |
          echo "Setting up pages configuration..."
      
      - name: Upload artifact
        run: |
          tar -czf github-pages.tar.gz -C _site .
          echo "artifact-path=github-pages.tar.gz" >> $GITHUB_OUTPUT
      
      - name: Deploy to GitHub Pages
        run: |
          echo "Deploying to GitHub Pages..."
          cd _site
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy Jekyll site"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
